apiVersion: batch/v1
kind: Job
metadata:
  name: rtdetr-job-jacket-increase-augment-shr-mgpus-2
  labels:
    k8s-app: rtdetr-job-jacket
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        k8s-app: rtdetr-job-jacket
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                    - NVIDIA-A100-SXM4-80GB
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/udembys/yolo
        command: ["/bin/sh", "-c"]
        args: ["cd /home;
            mv dataset/val/images/* dataset/train/images/; 
            mv dataset/val/labels/* dataset/train/labels/;
            git clone https://github.com/jacketdembys/helmets_challenge.git;
            cd helmets_challenge/scripts/;
            wandb login --cloud d7f81da19c5965b1c5eff37a677caab3ffb5379c;
            python -m torch.distributed.run --nproc_per_node 2 train_rtdetr.py -devices 2 -epochs 100 -imgsz 1920 -bs 24"]
        resources:
          limits:
            memory: "64Gi"
            cpu: "10"
            nvidia.com/gpu: "2"
          requests:
            memory: "64Gi"
            cpu: "10"
            nvidia.com/gpu: "2"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      restartPolicy: Never
