apiVersion: v1
kind: Pod
metadata: 
  name: yolo-pod-jacket
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A100-SXM4-80GB
            - NVIDIA-RTX-A6000
            - NVIDIA-RTX-A5000
            - NVIDIA-A40
            - NVIDIA-A10
            - NVIDIA-GeForce-RTX-3090
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/udembys/yolov8
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: 8
        nvidia.com/gpu: 1
      requests:
        memory: 32Gi
        cpu: 8
        nvidia.com/gpu: 1