apiVersion: v1
kind: Pod
metadata: 
  name: yolo-pod-jacket
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/udembys/yolo
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: 8
        nvidia.com/gpu: 1
      requests:
        memory: 32Gi
        cpu: 8
        nvidia.com/gpu: 1
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm