apiVersion: v1
kind: Pod
metadata: 
  name: yolo-pod-jacket
spec:
  tolerations:
  - key: nautilus.io/mizzou-vigir
    operator: Exists
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - gpn-fiona-mizzou-2.rnet.missouri.edu
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A100-SXM4-80GB
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/udembys/yolo
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: 8
        nvidia.com/gpu: 1
      requests:
        memory: 32Gi
        cpu: 8
        nvidia.com/gpu: 1
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm